apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../pdsl-helm
helmCharts:
  - name: sms-api-gateway-service-dev
    releaseName: sms-api-gateway-service
    namespace: dev
    valuesFile: values-dev.yaml
    additionalValuesFiles:
    - values-image.yaml
