apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../
helmCharts:
  - name: pdsl-helm
    releaseName: sms-subscrptn-prcng-plan-svc
    namespace: dev
    valuesFile: values-dev.yaml
    additionalValuesFiles:
    - values-image.yaml
