apiVersion: v1
kind: Service
metadata:
  name: {{ include "pdsl-app.fullname" . }}
  labels:
    app: {{ include "pdsl-app.name" . }}
    chart: {{ include "pdsl-app.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- if .Values.service.annotations }}
  annotations:
{{ toYaml .Values.service.annotations | indent 4 }}
{{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- if .Values.service.port}}
    - port: {{ .Values.service.port }}
      targetPort: app
      protocol: TCP
      name: app
    {{- end }}
    {{- if .Values.service.admin }}
    - port: {{ .Values.service.admin }}
      targetPort: admin
      protocol: TCP
      name: admin
    {{- end }}
    {{- if .Values.service.elbSSLTermination }}
    - port: {{ .Values.service.elbSSLTermination }}
      targetPort: app
      protocol: TCP
      name: https
    {{- end }}
    {{- if .Values.service.https }}
    - port: {{ .Values.service.https }}
      targetPort: https
      protocol: TCP
      name: https
    {{- end }}
    {{- range $key, $value := .Values.extraTCPPorts }}
    - port: {{ $value }}
      targetPort: {{ $key }}
      protocol: TCP
      name: {{ $key }}
    {{- end }}
    {{- range $key, $value := .Values.service.extraTCPPorts }}
    - port: {{ $value }}
      targetPort: {{ $key }}
      protocol: TCP
      name: {{ $key }}
    {{- end }}
  selector:
    app.kubernetes.io/name: {{ include "pdsl-app.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
