apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../pdsl-helm

helmCharts:
  - name: sms-messaging-service-dev
    namespace: dev
    releaseName: sms-messaging-service
    valuesFile: values-dev.yaml
    additionalValuesFiles:
    - values-image.yaml    
