apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmGlobals:
  chartHome: ../../pdsl-helm
helmCharts:
  - name: sms-user-service-dev
    namespace: dev
    releaseName: sms-user-service
    valuesFile: values-dev.yaml
    additionalValuesFiles:
    - values-image.yaml    
