apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
helmGlobals:
  chartHome: ../../
helmCharts:
  - name: pdsl-helm
    releaseName: sms-auth-service
    valuesFile: values-dev.yaml
    namespace: dev
    additionalValuesFiles:
    - values-image.yaml
